# Changes here will be overwritten by Copier
_commit: v0.3.1
_src_path: gh:deeplex/copier-cpp
email: henrik.gassmann@adesso.de
full_name: Henrik Gaßmann
header_config: false
header_only: false
namespace: vefs
project_name: vefs
project_slug: vefs
workaround_header: false
year: 2017-2023
