include:
  - project: 'templates/ci-job-templates'
    ref: master
    file: 'native-build-dep-vars.yml'

variables:
  VCPKG_VERSION: "2022.05.10"
  VCPKG_DEFAULT_BINARY_CACHE: C:\cache\vcpkg\archives
  VCPKG_DOWNLOADS: C:\cache\vcpkg\downloads


stages:
- build
- test
- upload

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_BRANCH !~ /^wip/'


########################################################################
# test template
.test: &test
  stage: test
  tags:
    - windows-docker


########################################################################
# build jobs
build:
  stage: build
  image: artifactory.adesso-group.com/mdk-dev-docker/de.mdk.bs/ci-win-native:vs17.2
  tags:
    - windows-docker
  before_script:
    - mkdir -Force "$env:VS_BUILD_TOOLS_ROOT\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer" *> $null
    - '& "$env:VS_BUILD_TOOLS_ROOT\Common7\Tools\Launch-VsDevShell.ps1" -VsInstallationPath "$env:VS_BUILD_TOOLS_ROOT" -Arch amd64 -HostArch amd64 *>$null'
    - mkdir -Force $env:VCPKG_DEFAULT_BINARY_CACHE,$env:VCPKG_DOWNLOADS *> $null
  script:
    - cmake --preset "x64-windows-msvc"
    - cmake --build --preset "x64-windows-msvc" --config Debug
    - cmake --build --preset "x64-windows-msvc" --config RelWithDebInfo
  artifacts:
    paths:
      - build/x64-windows-msvc/apps/Debug
      - build/x64-windows-msvc/apps/RelWithDebInfo
      - build/x64-windows-msvc/Debug
      - build/x64-windows-msvc/RelWithDebInfo
    expire_in: 1 week
    expose_as: binaries

# test jobs
test:debug:
  <<: *test
  script:
    - build\x64-windows-msvc\Debug\vefs-tests

test:release:
  <<: *test
  script:
    - build\x64-windows-msvc\RelWithDebInfo\vefs-tests

release:dev_tools:
  stage: upload
  tags:
    - windows-docker
  script:
    - iwr -H @{'X-JFrog-Art-Api'=$env:ARTIFACTORY_TOKEN} -method PUT -uri $env:ARTIFACTORY_URL/$env:ARTIFACTORY_GENERIC_REPO_KEY/dev-tools/vefs/vefs-cli.exe -Infile build\x64-windows-msvc\apps\RelWithDebInfo\vefs.exe
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
