include:
  - local: 'dependencies.yml'

stages:
- build
- test

build_debug:
  stage: build
  tags:
    - windows-torsten
  only:
    refs:
      - master
      - /^feature/
      - develop
      - merge_requests
  allow_failure: false
  script:
    - powershell iwr -H @{'X-JFrog-Art-Api'=$env:ARTIFACTORY_TOKEN} -method GET -uri https://mdk-bs-dev03.test-server.ag/artifactory/mdk-artifact-dev-local/de/mdk/bs/vefs/$env:VEFS_PACKAGES_VERSION/vefs_packages.zip -Outfile vefs-packages.zip
    - powershell Expand-Archive -LiteralPath 'vefs-packages.zip'
    - call mkdir build
    - call cd build
    - call cmake -G "Visual Studio 16 2019"  -A x64 -DVCPKG_TARGET_TRIPLET:STRING="x64-windows-ltcg-static" -DCMAKE_MSVC_RUNTIME_LIBRARY:STRING="MultiThreadedDebug" -DCMAKE_EXE_LINKER_FLAGS_DEBUG:STRING="/debug /INCREMENTAL" -DCMAKE_TOOLCHAIN_FILE="../vefs-packages/vefs_packages/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE="Debug" ".."
    - call cmake --build .
  artifacts:
    paths:
      - build/

test_debug:
  stage: test
  tags:
    - windows-torsten
  only:
    refs:
      - master
      - /^feature/
      - develop
      - merge_requests
  allow_failure: false
  script:
    - call build\bin\Debug\vefs-tests
  dependencies:
    - build_debug