include:
  - project: 'templates/ci-job-templates'
    ref: master
    file: 'native-build-dep-vars.yml'

variables:
  VCPKG_COMMIT_HASH: "807a7987612bbd702be9d9b8069124be62aff857"
  BUILD_PARALLELISM: "6"


stages:
- build
- test

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_BRANCH !~ /^wip/'


########################################################################
# build template
.build: &build
  stage: build
  tags:
    - windows-cpp-13
  before_script:
    - $ProgressPreference = "SilentlyContinue"
    - mkdir build
    - '[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12'
    - iwr -Method Get -Uri "https://github.com/microsoft/vcpkg/archive/$env:VCPKG_COMMIT_HASH.zip" -Outfile "build/vcpkg.zip"
    - 7z.exe x "build/vcpkg.zip" -obuild
    - mv "build/vcpkg-$VCPKG_COMMIT_HASH" "build/vcpkg"
    - $env:VCPKG_ROOT="$pwd\build\vcpkg"
    - cd build
    - '& vcpkg\bootstrap-vcpkg -disableMetrics'
    - '[IO.File]::WriteAllLines("$pwd\nuget.config", ''<?xml version="1.0" encoding="utf-8"?><configuration></configuration>'')'
    - $nuget=vcpkg\vcpkg fetch nuget | select -last 1
    - '& $nuget sources Add -Name MdkNugetV3 -Source "$ARTIFACTORY_URL/api/nuget/v3/$ARTIFACTORY_NUGET_REPO_KEY" -UserName $ARTIFACTORY_USER -Password $ARTIFACTORY_TOKEN -ConfigFile .\nuget.config'
    - '& $nuget config -Set "defaultPushSource=$ARTIFACTORY_URL/api/nuget/v3/$ARTIFACTORY_NUGET_REPO_KEY" -ConfigFile .\nuget.config'
    - $env:VCPKG_BINARY_SOURCES="clear;nugetconfig,$pwd\nuget.config,readwrite"
  artifacts: &build_artifacts
    paths:
      - build/bin
    expire_in: 1 week

# test template
.test: &test
  stage: test
  tags:
    - windows-cpp-13
  script:
    - build\bin\Debug\vefs-tests


########################################################################
# build jobs
build:debug:
  <<: *build
  script:
    - cmake -G "Visual Studio 16 2019"  -A x64 -DVCPKG_TARGET_TRIPLET:STRING="x64-windows-ltcg-static" -DCMAKE_MSVC_RUNTIME_LIBRARY:STRING="MultiThreadedDebug" -DCMAKE_EXE_LINKER_FLAGS_DEBUG:STRING="/debug /INCREMENTAL" -DBUILD_TESTING=ON ".."
    - cmake --build . -j $BUILD_PARALLELISM
  artifacts:
    <<: *build_artifacts
    expose_as: debug binaries

build:release:
  <<: *build
  script:
    - cmake -G "Visual Studio 16 2019"  -A x64 -DVCPKG_TARGET_TRIPLET:STRING="x64-windows-ltcg-static" -DCMAKE_MSVC_RUNTIME_LIBRARY:STRING="MultiThreaded" -DCMAKE_EXE_LINKER_FLAGS:STRING="/debug /INCREMENTAL" -DCMAKE_BUILD_TYPE="Release" -DBUILD_TESTING=ON ".."
    - cmake --build . -j $BUILD_PARALLELISM --config Release
  artifacts:
    <<: *build_artifacts
    expose_as: release binaries

# test jobs
test:debug:
  <<: *test
  script:
    - build\bin\Debug\vefs-tests
  needs: ["build:debug"]
  dependencies:
    - build:debug

test_release:
  <<: *test
  script:
    - build\bin\Release\vefs-tests
  needs: ["build:release"]
  dependencies:
    - build:release
