include:
  - project: 'templates/ci-job-templates'
    ref: master
    file: 'native-build-dep-vars.yml'

variables:
  VCPKG_VERSION: "2022.05.10"
  BUILD_PARALLELISM: "6"


stages:
- build
- test

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_BRANCH !~ /^wip/'


########################################################################
# build template
.build: &build
  stage: build
  tags:
    - windows-cpp-13
  before_script:
    - $ProgressPreference = "SilentlyContinue"
    - mkdir build
    - 'git clone --depth 1 --branch $VCPKG_VERSION https://github.com/microsoft/vcpkg.git build/vcpkg'
    - $env:VCPKG_ROOT="$pwd\build\vcpkg"
    - cd build
    - '& vcpkg\bootstrap-vcpkg -disableMetrics'

# test template
.test: &test
  stage: test
  tags:
    - windows-cpp-13
  script:
    - build\bin\Debug\vefs-tests


########################################################################
# build jobs
build:debug:
  <<: *build
  script:
    - cmake -G "Visual Studio 16 2019"  -A x64 -DVCPKG_TARGET_TRIPLET:STRING="x64-windows-static-lto" -DCMAKE_MSVC_RUNTIME_LIBRARY:STRING="MultiThreadedDebug" -DCMAKE_EXE_LINKER_FLAGS_DEBUG:STRING="/debug" -DBUILD_TESTING=ON -DWARNINGS_AS_ERRORS=ON ".."
    - cmake --build . -j $BUILD_PARALLELISM
  artifacts:
    paths:
      - build/Debug
    expire_in: 1 week
    expose_as: debug binaries

build:release:
  <<: *build
  script:
    - cmake -G "Visual Studio 16 2019"  -A x64 -DVCPKG_TARGET_TRIPLET:STRING="x64-windows-static-lto" -DCMAKE_MSVC_RUNTIME_LIBRARY:STRING="MultiThreaded" -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON -DCMAKE_EXE_LINKER_FLAGS:STRING="/debug" -DCMAKE_BUILD_TYPE="Release" -DBUILD_TESTING=ON -DWARNINGS_AS_ERRORS=ON ".."
    - cmake --build . -j $BUILD_PARALLELISM --config Release
  artifacts:
    paths:
      - build/Release
    expire_in: 1 week
    expose_as: release binaries

# test jobs
test:debug:
  <<: *test
  script:
    - build\Debug\vefs-tests
  needs: ["build:debug"]
  dependencies:
    - build:debug

test:release:
  <<: *test
  script:
    - build\Release\vefs-tests
  needs: ["build:release"]
  dependencies:
    - build:release
